name:                Lambdabox
version:             0.1.0.0
github:              "ItsMeijers/Lambdabox"
license:             BSD3
author:              "Thomas Meijers"
maintainer:          "thomasmeijers@live.nl"
copyright:           "2018 Thomas Meijers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ItsMeijers/Lambdabox#readme>

dependencies:
- base >= 4.7 && < 5
- wreq >= 0.5.2.1 && < 6
- time
- lens
- aeson
- lens-aeson
- text
- containers
- bytestring
- http-client
- vector
- mtl
- cryptonite

library:
  source-dirs: src

executables:
  Lambdabox-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lambdabox

tests:
  Lambdabox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Lambdabox
