{-# LANGUAGE MultiParamTypeClasses #-}

module Lambdabox.Trade.Tradeable
    ( Tradeable(..)
    ) where

import Lambdabox.Box
import Lambdabox.Exchange
import Lambdabox.Symbol

-- | The Tradeable class provides the possibilty of trading a pair of cryptos
-- on a specific exchange.
class (Symbol a, Symbol b, Exchange e) => Tradeable e a b

instance Tradeable Binance KEY BTC
instance Tradeable Binance ETH BTC
instance Tradeable Binance EOS BTC
instance Tradeable Binance TRX BTC
instance Tradeable Binance ONT BTC
instance Tradeable Binance XRP BTC
instance Tradeable Binance ICX BTC
instance Tradeable Binance BNB BTC
instance Tradeable Binance BCC BTC
instance Tradeable Binance ADA BTC
instance Tradeable Binance XLM BTC
instance Tradeable Binance NEO BTC
instance Tradeable Binance LTC BTC
instance Tradeable Binance VEN BTC
instance Tradeable Binance ARN BTC
instance Tradeable Binance IOTA BTC
instance Tradeable Binance XMR BTC
instance Tradeable Binance NPXS BTC
instance Tradeable Binance TUSD BTC
instance Tradeable Binance THETA BTC
instance Tradeable Binance BQX BTC
instance Tradeable Binance NANO BTC
instance Tradeable Binance ETC BTC
instance Tradeable Binance LUN BTC
instance Tradeable Binance INS BTC
instance Tradeable Binance WAVES BTC
instance Tradeable Binance ZRX BTC
instance Tradeable Binance ZIL BTC
instance Tradeable Binance WAN BTC
instance Tradeable Binance QKC BTC
instance Tradeable Binance DATA BTC
instance Tradeable Binance GTO BTC
instance Tradeable Binance MCO BTC
instance Tradeable Binance DASH BTC
instance Tradeable Binance CMT BTC
instance Tradeable Binance SNT BTC
instance Tradeable Binance GVT BTC
instance Tradeable Binance AION BTC
instance Tradeable Binance MDA BTC
instance Tradeable Binance QLC BTC
instance Tradeable Binance ENG BTC
instance Tradeable Binance STRAT BTC
instance Tradeable Binance EDO BTC
instance Tradeable Binance BRD BTC
instance Tradeable Binance XVG BTC
instance Tradeable Binance IOTX BTC
instance Tradeable Binance IOST BTC
instance Tradeable Binance QTUM BTC
instance Tradeable Binance ELF BTC
instance Tradeable Binance NAV BTC
instance Tradeable Binance NCASH BTC
instance Tradeable Binance NAS BTC
instance Tradeable Binance BCN BTC
instance Tradeable Binance WTC BTC
instance Tradeable Binance SUB BTC
instance Tradeable Binance WABI BTC
instance Tradeable Binance CVC BTC
instance Tradeable Binance HSR BTC
instance Tradeable Binance LOOM BTC
instance Tradeable Binance MTL BTC
instance Tradeable Binance AGI BTC
instance Tradeable Binance NXS BTC
instance Tradeable Binance OMG BTC
instance Tradeable Binance AE BTC
instance Tradeable Binance BCPT BTC
instance Tradeable Binance AMB BTC
instance Tradeable Binance REP BTC
instance Tradeable Binance LSK BTC
instance Tradeable Binance RCN BTC
instance Tradeable Binance SKY BTC
instance Tradeable Binance BAT BTC
instance Tradeable Binance GNT BTC
instance Tradeable Binance POA BTC
instance Tradeable Binance MAN BTC
instance Tradeable Binance POWR BTC
instance Tradeable Binance SNM BTC
instance Tradeable Binance SC BTC
instance Tradeable Binance ZEC BTC
instance Tradeable Binance BLZ BTC
instance Tradeable Binance VIB BTC
instance Tradeable Binance BTG BTC
instance Tradeable Binance WINGS BTC
instance Tradeable Binance NULS BTC
instance Tradeable Binance PPT BTC
instance Tradeable Binance XEM BTC
instance Tradeable Binance WPR BTC
instance Tradeable Binance STEEM BTC
instance Tradeable Binance YOYO BTC
instance Tradeable Binance DGD BTC
instance Tradeable Binance NEBL BTC
instance Tradeable Binance STORM BTC
instance Tradeable Binance XZC BTC
instance Tradeable Binance KNC BTC
instance Tradeable Binance BTS BTC
instance Tradeable Binance ENJ BTC
instance Tradeable Binance LEND BTC
instance Tradeable Binance QSP BTC
instance Tradeable Binance GAS BTC
instance Tradeable Binance APPC BTC
instance Tradeable Binance TRIG BTC
instance Tradeable Binance SALT BTC
instance Tradeable Binance FUN BTC
instance Tradeable Binance KMD BTC
instance Tradeable Binance ARK BTC
instance Tradeable Binance ADX BTC
instance Tradeable Binance CND BTC
instance Tradeable Binance POE BTC
instance Tradeable Binance RLC BTC
instance Tradeable Binance ZEN BTC
instance Tradeable Binance REQ BTC
instance Tradeable Binance CDT BTC
instance Tradeable Binance TNT BTC
instance Tradeable Binance SYS BTC
instance Tradeable Binance VIA BTC
instance Tradeable Binance RPX BTC
instance Tradeable Binance LRC BTC
instance Tradeable Binance LINK BTC
instance Tradeable Binance TNB BTC
instance Tradeable Binance OST BTC
instance Tradeable Binance CLOAK BTC
instance Tradeable Binance AST BTC
instance Tradeable Binance PIVX BTC
instance Tradeable Binance FUEL BTC
instance Tradeable Binance GXS BTC
instance Tradeable Binance SNGL BTC
instance Tradeable Binance VIBE BTC
instance Tradeable Binance BNT BTC
instance Tradeable Binance DNT BTC
instance Tradeable Binance MTH BTC
instance Tradeable Binance CHAT BTC
instance Tradeable Binance GRS BTC
instance Tradeable Binance DLT BTC
instance Tradeable Binance EVX BTC
instance Tradeable Binance STORJ BTC
instance Tradeable Binance MOD BTC
instance Tradeable Binance ICN BTC
instance Tradeable Binance RDN BTC
instance Tradeable Binance OAX BTC
instance Tradeable Binance BCD BTC